#!/bin/bash

# Quick deployment checklist
# Run: ./checklist.sh

clear
echo "╔═══════════════════════════════════════════════════════╗"
echo "║     🎬 NETFLIX CLONE - DEPLOYMENT CHECKLIST 🎬        ║"
echo "╚═══════════════════════════════════════════════════════╝"
echo ""
echo "Mark each item as you complete it:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PHASE 1: CODE FIXES (DONE)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✅ Security fixes applied"
echo "  ✅ Build command fixed"
echo "  ✅ Vercel config updated"
echo "  ✅ Changes pushed to GitHub"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PHASE 2: RENDER BACKEND (YOUR TURN)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ⬜ Open Render dashboard"
echo "  ⬜ Go to netflix-clone-api service"
echo "  ⬜ Check Logs tab"
echo "  ⬜ Verify build completed successfully"
echo "  ⬜ Note: Start will fail (MongoDB not configured)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PHASE 3: MONGODB SETUP (YOUR TURN)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ⬜ Open MongoDB Atlas"
echo "  ⬜ Verify Cluster0 is active (green)"
echo "  ⬜ Click Connect → Connect your application"
echo "  ⬜ Copy connection string"
echo "  ⬜ Replace <password> with actual password"
echo "  ⬜ Add /netflix-clone before the ?"
echo "  ⬜ Go to Network Access"
echo "  ⬜ Add IP: 0.0.0.0/0 (Allow from anywhere)"
echo "  ⬜ Confirm and save"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PHASE 4: UPDATE RENDER (YOUR TURN)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ⬜ Go to Render Environment tab"
echo "  ⬜ Find MONGODB_URI variable"
echo "  ⬜ Click Edit (pencil icon)"
echo "  ⬜ Delete PostgreSQL string"
echo "  ⬜ Paste MongoDB connection string"
echo "  ⬜ Click Save Changes"
echo "  ⬜ Wait for auto-redeploy (5-8 min)"
echo "  ⬜ Verify status changes to Live (green)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PHASE 5: UPDATE VERCEL (YOUR TURN)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ⬜ Copy backend URL from Render"
echo "  ⬜ Open Vercel dashboard"
echo "  ⬜ Go to Settings → Environment Variables"
echo "  ⬜ Update VITE_BACKEND_URL"
echo "  ⬜ Set to: BACKEND_URL/api"
echo "  ⬜ Save changes"
echo "  ⬜ Go to Deployments tab"
echo "  ⬜ Redeploy latest"
echo "  ⬜ Wait for deployment (1-2 min)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PHASE 6: VERIFICATION (YOUR TURN)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ⬜ Test backend health endpoint"
echo "  ⬜ Visit frontend URL"
echo "  ⬜ Verify movies/TV shows load"
echo "  ⬜ Test login/register"
echo "  ⬜ Test watchlist functionality"
echo "  ⬜ Check console for errors"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "OPTIONAL: DEMO USER"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ⬜ Go to Render Shell tab"
echo "  ⬜ Run: cd server && npm run seed"
echo "  ⬜ Use demo credentials to test"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎉 When all items are checked, deployment is complete!"
echo ""
echo "📊 Quick Links:"
echo "  • Render:  https://dashboard.render.com"
echo "  • Vercel:  https://vercel.com/dashboard"
echo "  • MongoDB: https://cloud.mongodb.com"
echo "  • Live:    https://netflix-clone-hh1d.vercel.app"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
